### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/eth-simple-keyring#135]
We want to migrate this package to TypeScript to reduce regressions and improve compatibility with our other TypeScript projects.

**Comment by Gudahtt** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Shared-Libraries-621e46b4d7103800171d1b02/issues/MetaMask/eth-simple-keyring/135?planning-poker) with Zenhub @mcmire @cryptodev-2s

**Comment by HowardBraham** [comment]
Fixed by https://github.com/MetaMask/eth-simple-keyring/pull/140
