### ISSUE TITLE
ethereumjs-wallet dependency

### ISSUE THREAD

**Issue by kumavis** [MetaMask/eth-simple-keyring#21]
we currently use `ethereumjs-wallet` to:
- generate new keys
- get address from private key

this is pretty easy to do without this wrapper library and all that it brings with it

Also the current `ethereumjs-wallet` includes an old version of `aes-js` which modifies `Array.prototype`. Latest `aes-js` does not have this problem.

**Comment by lazaridiscom** [comment]
related: https://github.com/MetaMask/eth-hd-keyring/issues/7

**Comment by lazaridiscom** [comment]
see PR https://github.com/MetaMask/eth-simple-keyring/pull/33
